# Generated by Django 5.0.4 on 2024-01-18 19:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_name", models.CharField(max_length=100)),
                ("first_name", models.CharField(max_length=100)),
                ("group", models.CharField(max_length=100)),
                ("chosen_grade", models.IntegerField()),
                (
                    "registration_date",
                    models.DateTimeField(default=datetime.datetime.now),
                ),
                (
                    "grade_choice_date",
                    models.DateTimeField(default=datetime.datetime.now),
                ),
                ("assigned_tasks", models.JSONField(default=list)),
            ],
        ),
    ]
